"""인터랙티브 설정 마법사 — 최초 실행 시 API 키 입력."""

import os
import sys
from pathlib import Path

CONFIG_DIR = os.path.expanduser("~/.config/cheongyak-mcp")
CONFIG_FILE = os.path.join(CONFIG_DIR, ".env")


def _ensure_config_dir():
    Path(CONFIG_DIR).mkdir(parents=True, exist_ok=True)


def _load_env():
    env = {}
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    env[key.strip()] = value.strip()
    return env


def _save_env(env: dict):
    _ensure_config_dir()
    with open(CONFIG_FILE, "w") as f:
        f.write("# Cheongyak RAG MCP Configuration\n")
        f.write("# Generated by setup wizard\n\n")
        for key, value in env.items():
            f.write(f"{key}={value}\n")
    return CONFIG_FILE


def _prompt(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        value = input(f"{prompt}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    return value or default


def _yes_no(prompt: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    try:
        value = input(f"{prompt} ({hint}): ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    if not value:
        return default
    return value in ("y", "yes", "네", "예")


def run_setup() -> str:
    print()
    print("╔══════════════════════════════════════════════╗")
    print("║     청약 RAG MCP 서버 설정 마법사            ║")
    print("║     Cheongyak RAG MCP Setup Wizard           ║")
    print("╚══════════════════════════════════════════════╝")
    print()

    env = _load_env()

    # 1. 데이터 소스 선택
    print("━━━ 1/3. 데이터 소스 설정 ━━━")
    print()
    print("공공데이터포털(data.go.kr) 공식 API 키가 있으면")
    print("안정적인 정형 데이터를 받을 수 있습니다.")
    print("키가 없어도 청약홈 스크래핑으로 바로 사용 가능합니다.")
    print()

    has_api_key = _yes_no("공공데이터포털 API 키가 있으신가요?", default=False)

    if has_api_key:
        api_key = _prompt("  API 키 (인증키/Decoding)를 입력하세요")
        if api_key:
            env["DATA_GO_KR_API_KEY"] = api_key
            print("  ✅ 공식 API 모드로 설정됩니다.")
        else:
            print("  ⚠️  빈 값으로 스크래핑 모드로 진행합니다.")
    else:
        print()
        print("  👉 공식 API 키 발급 방법 (무료):")
        print("     1. https://www.data.go.kr 회원가입")
        print("     2. '아파트분양정보' 검색 → '활용신청'")
        print("     3. 마이페이지 → 인증키(Decoding) 복사")
        print("     4. 나중에 설정 변경: cheongyak-mcp config")
        print()
        print("  🔧 스크래핑 모드로 계속 진행합니다.")
        env["DATA_GO_KR_API_KEY"] = ""

    # 2. OpenAI (RAG Q&A)
    print()
    print("━━━ 2/3. RAG Q&A 설정 (선택) ━━━")
    print()
    print("OpenAI API 키를 입력하면 공고문 기반 AI 요약 답변이 가능합니다.")
    print("키가 없으면 검색 결과만 표시됩니다.")
    print()

    has_openai = _yes_no("OpenAI API 키를 설정하시겠습니까?", default=False)
    if has_openai:
        openai_key = _prompt("  OpenAI API 키")
        if openai_key:
            env["OPENAI_API_KEY"] = openai_key
            env["LLM_MODEL"] = _prompt("  LLM 모델", "gpt-4o-mini")
            env["LLM_BASE_URL"] = _prompt("  API Base URL", "https://api.openai.com/v1")
            print("  ✅ RAG Q&A가 활성화됩니다.")
        else:
            env["OPENAI_API_KEY"] = ""
    else:
        env["OPENAI_API_KEY"] = env.get("OPENAI_API_KEY", "")

    # 3. 경로 설정
    print()
    print("━━━ 3/3. 데이터 경로 ━━━")
    print()

    default_docs = env.get("DOCUMENTS_DIR", "./data/documents")
    default_db = env.get("CHROMA_PERSIST_DIR", "./data/chroma_db")

    docs_dir = _prompt("  문서 저장 경로", default_docs)
    db_dir = _prompt("  ChromaDB 경로", default_db)

    env["DOCUMENTS_DIR"] = docs_dir
    env["CHROMA_PERSIST_DIR"] = db_dir
    env["EMBEDDING_MODEL"] = env.get("EMBEDDING_MODEL", "jhgan/ko-sroberta-multitask")
    env["CACHE_TTL_MINUTES"] = env.get("CACHE_TTL_MINUTES", "30")

    # 저장
    config_path = _save_env(env)

    # 완료
    print()
    print("╔══════════════════════════════════════════════╗")
    print("║            설정이 완료되었습니다!             ║")
    print("╚══════════════════════════════════════════════╝")
    print()
    print(f"  📁 설정 파일: {config_path}")
    print()

    if env.get("DATA_GO_KR_API_KEY"):
        print("  📊 데이터 소스: 공식 API + 스크래핑")
    else:
        print("  📊 데이터 소스: 청약홈 스크래핑 (공식 API 키 없음)")

    if env.get("OPENAI_API_KEY"):
        print("  🤖 RAG Q&A: 활성화")
    else:
        print("  🤖 RAG Q&A: 비활성화 (검색 결과만)")

    print()
    print("  설정 변경: cheongyak-mcp config")
    print()

    return config_path


def is_first_run() -> bool:
    return not os.path.exists(CONFIG_FILE)


def get_env_file() -> str:
    return CONFIG_FILE
